### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by FlorianHeigl** [mirage/xen-arm-builder#80]
I ran into some build error during ```make build```

When working with Alpine 3.4.0 it looks like this:

```
scripts/Makefile.build:258: recipe for target 'arch/arm/kernel/setup.o' failed
make[1]: *** [arch/arm/kernel/setup.o] Error 1
make[1]: *** Waiting for unfinished jobs....
(cat /dev/null; ) > arch/arm/mach-sunxi/modules.order
cc1: some warnings being treated as errors
scripts/Makefile.build:258: recipe for target 'arch/arm/mm/mmu.o' failed
make[1]: *** [arch/arm/mm/mmu.o] Error 1
In file included from arch/arm/kernel/module.c:24:0:
./arch/arm/include/asm/sections.h: In function 'in_entry_text':
./arch/arm/include/asm/sections.h:18:9: error: implicit declaration of function 'memory_contains' [-Werror=implicit-function-declaration]
  return memory_contains(__entry_text_start, __entry_text_end,
         ^~~~~~~~~~~~~~~
In file included from arch/arm/kernel/smp.c:43:0:
./arch/arm/include/asm/sections.h: In function 'in_entry_text':
./arch/arm/include/asm/sections.h:18:9: error: implicit declaration of function 'memory_contains' [-Werror=implicit-function-declaration]
  return memory_contains(__entry_text_start, __entry_text_end,
         ^~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
scripts/Makefile.build:258: recipe for target 'arch/arm/kernel/module.o' failed
make[1]: *** [arch/arm/kernel/module.o] Error 1
   arm-linux-gnueabi-ld -EL    -r -o arch/arm/mach-sunxi/built-in.o arch/arm/mach-sunxi/sunxi.o arch/arm/mach-sunxi/platsmp.o 
Makefile:944: recipe for target 'arch/arm/mm' failed
make: *** [arch/arm/mm] Error 2
cc1: some warnings being treated as errors
scripts/Makefile.build:258: recipe for target 'arch/arm/kernel/smp.o' failed
make[1]: *** [arch/arm/kernel/smp.o] Error 1
Makefile:944: recipe for target 'arch/arm/kernel' failed
make: *** [arch/arm/kernel] Error 2
Makefile:18: recipe for target 'build' failed
make: *** [build] Error 2

```

It also happens - at a different spot - when working with the current Alpine 3.9.3 tarball.
What i can tell is that it relates to some KVM modules.

```
 arm-linux-gnueabi-gcc -Wp,-MD,arch/arm/kvm/.interrupts.o.d  -nostdinc -isystem /usr/lib/gcc-cross/arm-linux-gnueabi/6/include -I./arch/arm/include -Iarch/arm/include/generated/uapi -Iarch/arm/include/generated  -Iinclude -I./arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian   -D__ASSEMBLY__ -mabi=aapcs-linux -mno-thumb-interwork -mfpu=vfp -funwind-tables -marm -D__LINUX_ARM_ARCH__=7 -march=armv7-a  -include asm/unified.h -msoft-float -DCC_HAVE_ASM_GOTO         -Wa,-march=armv7-a+virt   -c -o arch/arm/kvm/interrupts.o arch/arm/kvm/interrupts.S
In file included from arch/arm/kernel/setup.c:44:0:
./arch/arm/include/asm/sections.h: In function 'in_entry_text':
./arch/arm/include/asm/sections.h:18:9: error: implicit declaration of function 'memory_contains' [-Werror=implicit-function-declaration]
  return memory_contains(__entry_text_start, __entry_text_end,
         ^~~~~~~~~~~~~~~
In file included from arch/arm/mm/init.c:31:0:
./arch/arm/include/asm/sections.h: In function 'in_entry_text':
./arch/arm/include/asm/sections.h:18:9: error: implicit declaration of function 'memory_contains' [-Werror=implicit-function-declaration]
  return memory_contains(__entry_text_start, __entry_text_end,
         ^~~~~~~~~~~~~~~
```

could you help me on this, for one by verifying you see the same issue?
Only detail i can think of is I have set ```TARGET=Cubietruck```

Will update once/if i find more relevant info.

**Comment by FlorianHeigl** [comment]
this is sorted, deleted the whole src/ and it built. (likely make clean should go down to the linux source folder)
i don't know how to write make otherwise i'd add that ;-)
